routes/web.php
<?php

use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
Route::resource('invoices', InvoiceController::class);

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Invoice extends Model
{
    protected $guarded = ['id'];
    public function items(): HasMany
    {
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Invoice;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        try {
            $invoice = Invoice::withCount('items')->get();
            return view('invoices.index', ['invoices' => $invoice])->with('messege','Invoices Featched Successfully');
        } catch (\Exception $e) {
            throw($e);
            Log::error('Error occurred while storing invoice: ',['erroe' => $e->getMessage()]);
            return redirect()->back()->with('messege', 'Something Went Wrong');
        }
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        try {
            $invoice = Invoice::latest()->first('id');
            $id =!empty($invoice->id)? ++$invoice->id : 1;
            return view('invoices.create', ['id' => $id]);
        } catch (\Exception $e) {
            throw($e);
            Log::error('Error occurred while storing invoice: ' ,['erroe' => $e->getMessage()]);
            return redirect()->back()->with('messege', 'Something Went Wrong');
        }
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'image'         => 'required|image|max:2048',
                'bill_from'     => 'required|string',
                'bill_to'       => 'required|string',
                'date'          => 'required|date',
                'payment_type'  => 'required|string',
                'due_date'      => 'required|date',
                'po_number'     => 'nullable|numeric',
                'notes'         => 'nullable|string',
                'terms'         => 'nullable|string',
                'sub_total'     => 'required|numeric',
                'discount'      => 'nullable|numeric',
                'tax'           => 'nullable|numeric',
                'shipping'       => 'nullable|numeric',
                'total'         => 'required|numeric',
                'paid_amount'   => 'nullable|numeric',
                'due_amount'    => 'required|numeric',
                'items.*.item_name'  => 'required',
                'items.*.quantity'   => 'required|numeric',
                'items.*.rate'       => 'required|numeric',
                'items.*.amount'     => 'required|numeric',
            ],
            [
                'items.*.item_name.required' => 'The item name field is required',
                'items.*.quantity.required'  => 'The quantity field is required',
                'items.*.rate.required'      => 'The rate field is required',
                'items.*.amount.required'    => 'The amount field is required',
            ]
        );
        try {
            DB::beginTransaction();
            $requestData = $request->except(['_token', 'items']);
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $path = Storage::disk('public')->put('images', $image);
                $requestData['image'] = $path;
            }
            if (empty($requestData['paid_amount'])) {
                $requestData['paid_amount'] = 0;
            }
            $model = Invoice::create($requestData);
            foreach ($request->items as $item) {
                $id = $model->id;
                $item = array_merge(['invoice_id' => $id], $item);
                $model->items()->create($item);
            }
            DB::commit();
            return redirect('invoices')->with('message', 'Invoices Created Successfully');
        } catch (\Exception $e) {
            DB::rollBack();
            throw($e);
            Log::error('Error occurred while storing invoice: ',['erroe' => $e->getMessage()]);
            return redirect()->back()->with('messege', 'Something Went Wrong');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Invoice $invoice)
    {
        try {
            $invoice = $invoice->with('items')->where('id', $invoice->id)->get();
            return view('invoices.show', ['invoices' => $invoice])->with('messege','Invoices Show Successfully');;
        } catch (\Exception $e) {
            throw($e);
            Log::error('Error occurred while storing invoice: ' ,['erroe' => $e->getMessage()]);
            return redirect()->back()->with('messege', 'Something Went Wrong');
        }
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Invoice $invoice)
    {
        try {
        $invoice = $invoice->with('items')->where('id', $invoice->id)->get();
        return view("invoices.edit", ['invoice' => $invoice]);
    } catch (\Exception $e) {
        throw($e);
        Log::error('Error occurred while storing invoice: ' ,['erroe' => $e->getMessage()]);
        return redirect()->back()->with('messege', 'Something Went Wrong');
    }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Invoice $invoice)
    {
        $request->validate(
            [
                'image'         => 'nullable|image|max:2048',
                'bill_from'     => 'required|string',
                'bill_to'       => 'required|string',
                'date'          => 'required|date',
                'payment_type'  => 'required|string',
                'due_date'      => 'required|date',
                'po_number'     => 'nullable|numeric',
                'notes'         => 'nullable|string',
                'terms'         => 'nullable|string',
                'sub_total'     => 'required|numeric',
                'discount'      => 'nullable|numeric',
                'tax'           => 'nullable|numeric',
                'shipping'       => 'nullable|numeric',
                'total'         => 'required|numeric',
                'paid_amount'   => 'nullable|numeric',
                'due_amount'    => 'nullable|numeric',
                'items.*.item_name'  => 'required',
                'items.*.quantity'   => 'required|numeric',
                'items.*.rate'       => 'required|numeric',
                'items.*.amount'     => 'required|numeric',
            ],
            [
                'items.*.item_name.required' => 'The item name field is required',
                'items.*.quantity.required'  => 'The quantity field is required',
                'items.*.rate.required'      => 'The rate field is required',
                'items.*.amount.required'    => 'The amount field is required',
            ]
        );
        try {
            DB::beginTransaction();
            $requestData = $request->except(['_token', 'items']);
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $path = Storage::disk('public')->put('images', $image);
                $requestData['image'] = $path;
            }
            if (empty($requestData['paid_amount'])) {
                $requestData['paid_amount'] = 0;
            }
            $invoice->update($requestData);
            if($request->uid){
            foreach ($request->uid as $value) {
                $invoice->items()->where('id',$value)->delete();
            }
        }
            foreach ($request->items as $item) {
                $invoice->items()->updateOrCreate(['id' => $item['id']], $item);
            }
            DB::commit();
            return redirect('invoices')->with('message', 'Invoices Fetched Successfully');
        } catch (\Exception $e) {
            DB::rollBack();
            throw($e);
            Log::error('invoice_update_exception',['erroe' => $e->getMessage()]);
            return redirect()->back()->with('messege', 'Something Went Wrong');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Invoice $invoice)
    {
        try {
            DB::beginTransaction();
            $invoice->items()->delete();
            $invoice->delete();
            DB::commit();
            return redirect('invoices')->with('message', 'Invoices Deleted Successfully');

        } catch (\Exception $e) {
            DB::rollBack();
            throw($e);
            Log::error('Delete_invoice_error',['erroe' => $e->getMessage()]);
            return redirect()->back();
        }
    }
}

resources/views/invoices/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('boot/css/bootstrap.min.css')}}">
    <script src="{{ asset('boot/js/bootstrap.min.js')}}"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/invoice.js') }}"></script>
    <style>
    .x {
        display: none;
    }

    tr:hover .x {
        display: block;
    }
    </style>
</head>


<body class="bg-body-secondary lead d-flex">

    <div class="col-sm-11 border border-gray ms-5 p-5 mt-2 bg-body-tertiary d-flex row gap-3">
        @if (session('message'))
        <div class="alert alert-danger">
            {{ session('message') }}
        </div>
        @endif
        <form action="{{ route('invoices.store') }}" method="post" id="form_data" enctype="multipart/form-data">
            @csrf
            <div>
                <div id="imageFile" class="col-4">
                    <img src="" id="imageDisplay" class="col-2" alt="">
                    <input type="file" name="image" id="image" hidden>
                    <label for="image" id="imageLabel"
                        class="border border-gray col-sm-3 text-center fw-bold">Image</label>
                    @error('image')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <div class="d-flex P-2">
                <div class="col-sm-7 ps-2 row gap-3">
                    <div>
                        <span class="col fw-bold">Bill From</span><br>
                        <textarea name="bill_from" id="bill_from" cols="30" rows="2"
                            placeholder="Bill From">{{ old('bill_from') }}</textarea>
                        @error('bill_from')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div>
                        <span class="col fw-bold">Bill To</span><br>
                        <textarea name="bill_to" id="bill_to" cols="30" rows="2"
                            placeholder="Bill To">{{ old('bill_to') }}</textarea>
                        @error('bill_to')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div>
                        <span class="col fw-bold">Ship To</span><br>
                        <textarea name="ship_to" id="ship_to" cols="30" rows="2"
                            placeholder="Ship To">{{ old('ship_to') }}</textarea>
                        @error('ship_to')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm-5 ps-2 row gap-1">
                    <div class="col-3 offset-sm-8 ">
                        <p class="fw-bold"><b>INVOICE</b></p>
                    </div>
                    <div class="row gx-4  ">
                        <span class="col fw-bold">#</span>
                        <input class="col h-2em" type="number" id="id" value="{{ $id }}" readonly>
                    </div>
                    <div class="row gx-4">
                        <span class="col fw-bold">Date</span>
                        <input class="col" type="date" name="date" id="date" value="{{ old('date') }}">
                        @error('date')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="row gx-4 ">
                        <span class="col fw-bold">Payment Type</span>
                        <input class="col" type="text" name="payment_type" id="payment_type" placeholder="Payment Type"
                            value="{{ old('payment_type') }}">
                        @error('payment_type')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="row gx-4 ">
                        <span class="col fw-bold">Due Date</span>
                        <input class="col" type="date" name="due_date" id="due_date" value="{{ old('due_date') }}">
                        @error('due_date')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="row gx-4 ">
                        <span class="col fw-bold">PO Number</span>
                        <input class="col" type="number" name="po_number" id="po_number" value="{{ old('po_number') }}">
                        @error('po_number')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class=" row gap-2 d-grid">
                <table id="table_data" class="col">
                    <tr>
                        <th>Item</th>
                        <th>Quantity</th>
                        <th>Rate</th>
                        <th>Amount</th>
                    </tr>
                    <tr class="">
                        <td>
                            <input type="text" name="items[0][item_name]" class="item_name"
                                value="{{ old('items.0.item_name') }}" placeholder="Item">
                            @error('items.*.item_name')
                            <br> <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </td>
                        <td>
                            <input type="number" name="items[0][quantity]" class="quantity"
                                value="{{ old('items.0.quantity') }}" placeholder="Quantity">
                            @error('items.*.quantity')
                            <br> <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </td>
                        <td>
                            <input type="number" name="items[0][rate]" class="rate" value="{{ old('items.0.rate') }}"
                                placeholder="Rate">
                            @error('items.*.rate')
                            <br>
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </td>
                        <td>
                            <input type="number" name="items[0][amount]" class="amount"
                                value="{{ old('items.0.amount') }}" placeholder="Amount">
                            @error('items.*.amount')
                            <br>
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </td>
                        <td>
                            <div class=" x text-dark border-teansprant">&#x2718; </div>
                        </td>
                    </tr>
                </table>
                <div class="text-dark border border-gray text-body-tertiary col-1 fw-bold button " id="button">Click Me
                </div>
            </div>
            <div class="d-flex P-2 ">
                <div class="col-sm-7 ps-2 row gap-3">
                    <div>
                        <span class="col fw-bold">Notes</span><br>
                        <textarea name="notes" id="notes" cols="30" rows="2"
                            placeholder="Notes">{{ old('notes') }}</textarea>
                        @error('notes')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div>
                        <span class="col fw-bold">Terms</span><br>
                        <textarea name="terms" id="terms" cols="30" rows="2"
                            placeholder="Terms">{{ old('terms') }}</textarea>
                        @error('terms')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm-5 ps-2 row gap-1 invoice_bill">
                    <div class="row gx-4 ">
                        <span class="col fw-bold">Sub Total</span>
                        <input class="col" type="number" name="sub_total" id="sub_total" placeholder="Sub Total"
                            value="{{ old('sub_total') }}" readonly>
                        @error('sub_total')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="ps-7 fw-bold d-grid">
                        <div class="row">
                            <div class="col-12 float-lg-end">
                                <div class="d-grid float-lg-end  ">
                                    <span class="discount"> + Discount</span>
                                    <span class="discount_field"></span>
                                    <span class="tax"> + Tax</span>
                                    <span class="tax_field"></span>
                                    <span class="shipping"> + Shipping</span>
                                    <span class="shipping_field"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row gx-4 ">
                        <span class="col fw-bold">Total</span>
                        <input class="col" type="number" name="total" id="total" value="{{ old('total') }}"
                            placeholder="Total">
                        @error('total')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="row gx-4 ">
                        <span class="col fw-bold">Paid Amount</span>
                        <input class="col" type="number" name="paid_amount" id="paid_amount" placeholder="Paid Amount"
                            value="{{ old('paid_amount') }}">
                        @error('paid_amount')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="row gx-4 ">
                        <span class="col fw-bold">Due Amount</span>
                        <input class="col" type="number" name="due_amount" id="due_amount" placeholder="Due Amount"
                            value="{{ old('due_amount') }}">
                        @error('due_amount')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
            </div>
            <div>
                <div>
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
</body>

</html>

resources/views/invoices/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoices</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        @if (session('message'))
        <div id="alertMessage" class="alert alert-danger">{{ session('message') }}</div>
        @endif
        <div class="d-flex justify-content-between align-items-center mt-3">
            <h1 class="mb-0">INVOICES</h1>
            <a href="{{ route('invoices.create') }}" class="btn btn-primary">Create New Invoice</a>
        </div>
        <br>

        <div class="table-responsive">
            <table class="table table-bordered">
                <thead class="table-dark">
                    <tr>
                        <th>Id</th>
                        <th>Bill From</th>
                        <th>Bill To</th>
                        <th>Ship To</th>
                        <th>Date</th>
                        <th>Payment Type</th>
                        <th>Due Date</th>
                        <th>PO Number</th>
                        <th>Notes</th>
                        <th>Terms</th>
                        <th>Sub Total</th>
                        <th>Discount</th>
                        <th>Tax</th>
                        <th>Shipping</th>
                        <th>Total</th>
                        <th>Pay Amount</th>
                        <th>Due Amount</th>
                        <th>Total Items</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($invoices as $invoice)
                    <tr>
                        <td>{{ $invoice->id }}</td>
                        <td>{{ $invoice->bill_from }}</td>
                        <td>{{ $invoice->bill_to }}</td>
                        <td>{{ $invoice->ship_to }}</td>
                        <td>{{ $invoice->date }}</td>
                        <td>{{ $invoice->payment_type }}</td>
                        <td>{{ $invoice->due_date }}</td>
                        <td>{{ $invoice->po_number }}</td>
                        <td>{{ $invoice->notes }}</td>
                        <td>{{ $invoice->terms }}</td>
                        <td>{{ $invoice->sub_total }}</td>
                        <td>{{ $invoice->discount }}</td>
                        <td>{{ $invoice->tax }}</td>
                        <td>{{ $invoice->shipping }}</td>
                        <td>{{ $invoice->total }}</td>
                        <td>{{ $invoice->paid_amount }}</td>
                        <td>{{ $invoice->due_amount }}</td>
                        <td>{{ $invoice->items_count }}</td>
                        <td>
                            <form action="{{ route('invoices.destroy',$invoice->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                            <a href="{{ route('invoices.show',$invoice->id) }}" class="btn btn-info">Show</a>
                            <a href="{{ route('invoices.edit',$invoice->id) }}" class="btn btn-warning">Edit</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <!-- Bootstrap JS (Optional - if you need any Bootstrap JavaScript components) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var alertMessage = document.getElementById('alertMessage');
        if (alertMessage) {
            setTimeout(function() {
                alertMessage.style.display = 'none';
            }, 5000);
        }
    });
</script>
</body>
</html>

resources/views/invoices/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Advanced Invoice</title>
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
  }
  .invoice-container {
    width: 80%;
    margin: 20px auto;
    border: 1px solid #ccc;
    padding: 20px;
    background-color: #fff;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
  .invoice-header {
    text-align: center;
    margin-bottom: 20px;
  }
  .invoice-header h1 {
    margin: 0;
    color: #333;
  }
  .invoice-details {
    display: flex;
    justify-content: space-between;
    margin-bottom: 20px;
  }
  .invoice-details .left,
  .invoice-details .right {
    width: 35%;
  }
  .invoice-details .right2 {
    width: 25%;
  }
  .invoice-items {
    margin-bottom: 20px;
  }
  .invoice-items table {
    width: 100%;
    border-collapse: collapse;
  }
  .invoice-items th,
  .invoice-items td {
    padding: 8px;
    border-bottom: 1px solid #ddd;
    text-align: left;
  }
  .invoice-items th {
    background-color: #f2f2f2;
  }
  .invoice-total {
    display: block;
    justify-content: flex-end;
    margin-top: 20px;
  }
  .invoice-total p {
    font-weight: bold;
  }

  .download-btn {
    display: block;

    width: 48%;
    padding: 10px;
    text-align: center;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }
  .download-btn:hover {
    background-color: #0056b3;
  }
  .dow-save{
    display: flex;
    gap: 2%;
    padding-left: 1%;
  }
  textarea{
    border: 0px;
    padding: 2%;
  }
</style>
</head>
<body>
@foreach ($invoices as $invoice )

@endforeach
<div class="invoice-container">
  <div class="invoice-header">
    <h1>Invoice </h1>
    <img src="{{ asset('storage/' . $invoice->image) }}" id="imageDisplay" class="col-2" alt="" width="50px">
  </div>
  <div class="invoice-details">
    <div class="left">
    <p><strong>Billed To:</strong> {{$invoice->bill_to}}</p>
    <p><strong>Billed To:</strong> {{$invoice->bill_to}}</p>
      <p><strong>Ship To:</strong> {{$invoice->ship_to}}</p>
      <p><strong>Invoice Date:</strong> {{$invoice->date}} </p>
    </div>
    <div class="right">
    <p><strong>Invoice Number:</strong> {{$invoice->id}} </p>
    <p><strong>Payment Type:</strong> {{$invoice->payment_type}} </p>
       <p><strong>Due Date:</strong> {{$invoice->due_date}} </p>
      <p><strong>Po Number:</strong> {{$invoice->po_number}} </p>
    </div>
  </div>
  <div class="invoice-items">
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Quantity</th>
          <th>Unit Price</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($invoice->items as $item)
        <tr>
          <td>{{ $item->item_name}}</td>
          <td>{{ $item->quantity}}</td>
          <td>{{ $item->rate}}</td>
          <td>{{ $item->amount}}</td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
  <div class="invoice-details">
    <div class="left">
    <p><strong>Notes:</strong><br>
    <textarea  cols="35" rows="6" readonly>{{$invoice->notes}}</textarea>
   </p>
   <p><strong>Terms:</strong><br>
    <textarea  cols="35" rows="6" readonly>{{$invoice->terms}}</textarea>
   </p>
    </div>
    <div class="right2" style=" margin-left: 20px;">
    <p><strong>Sum Total:</strong>{{$invoice->sub_total}}</p>
    <p><strong>Discount:</strong> {{$invoice->discount}}</p>
    <p><strong>Tax:</strong>{{$invoice->tax}}</p>
    <p><strong>shipping:</strong>{{$invoice->shipping}}</p>
    <p><strong>Total:</strong> {{$invoice->total}}</p>
    <p><strong>Pad Amount:</strong>{{$invoice->paid_amount}}</p>
    <p><strong>Due Amount:</strong>{{$invoice->due_amount}}</p>
    </div>
  </div>
  <div class="invoice-total">

  </div>
  <div class="dow-save">
  <button class="download-btn" onclick="downloadPDF()">Download PDF</button><br>
  <button class="download-btn" onclick="printInvoice()">Print Invoice</button>
</div>
</div>
<script>
  function printInvoice() {
    window.print();
  }
</script>

<script>
  function downloadPDF() {
    var element = document.querySelector('.invoice-container');
    html2pdf()
      .from(element)
      .save('invoice.pdf');
  }
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js"></script>

</body>
</html>